// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: password.proto

#import "GPBProtocolBuffers.h"

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30000
#error This file was generated by a different version of protoc-gen-objc which is incompatible with your Protocol Buffer sources.
#endif

// @@protoc_insertion_point(imports)

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - PasswordRoot

@interface PasswordRoot : GPBRootObject

// The base class provides:
//   + (GPBExtensionRegistry *)extensionRegistry;
// which is an GPBExtensionRegistry that includes all the extensions defined by
// this file and all files that it depends on.

@end

#pragma mark - PasswordCache

typedef GPB_ENUM(PasswordCache_FieldNumber) {
  PasswordCache_FieldNumber_ItemsArray = 1,
};

// 全局数据缓存
@interface PasswordCache : GPBMessage

// |itemsArray| contains |PasswordItem|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *itemsArray;
@property(nonatomic, readonly) NSUInteger itemsArray_Count;

@end

#pragma mark - PasswordItem

typedef GPB_ENUM(PasswordItem_FieldNumber) {
  PasswordItem_FieldNumber_EncodedText = 1,
  PasswordItem_FieldNumber_PasswordTitle = 2,
  PasswordItem_FieldNumber_PasswordLink = 3,
  PasswordItem_FieldNumber_Timestamp = 4,
  PasswordItem_FieldNumber_UserName = 5,
};

// 密码对象存储
@interface PasswordItem : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *encodedText;

@property(nonatomic, readwrite, copy, null_resettable) NSString *passwordTitle;

@property(nonatomic, readwrite, copy, null_resettable) NSString *passwordLink;

@property(nonatomic, readwrite) int64_t timestamp;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userName;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

// @@protoc_insertion_point(global_scope)
